version: '3.9'
services:
  openindoor:
    build: .
    image: josm-openindoor-plugin
    working_dir: /openindoor/josm/plugins/openindoor
    entrypoint: bash -c
    command:
    - |
      ant dist
      mkdir -p ./dist
      cp /openindoor/josm/dist/openindoor.jar ./dist/
    volumes:
    - ./plugins/openindoor:/openindoor/josm/plugins/openindoor
